// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase URL or Key missing!", { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY });
}

// Clean up any potential extra quotes from env vars if they exist
const cleanUrl = (SUPABASE_URL?.replace(/"/g, '') || '').trim();
const cleanKey = (SUPABASE_PUBLISHABLE_KEY?.replace(/"/g, '') || '').trim();

export const supabase = createClient<Database>(cleanUrl, cleanKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});